// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Z3WJXCvhuV09AuP13w1BdKnoHQxYsO0',
    appId: '1:137420687739:web:6289e41799aba88fe155de',
    messagingSenderId: '137420687739',
    projectId: 'simple-app-5892c',
    authDomain: 'simple-app-5892c.firebaseapp.com',
    storageBucket: 'simple-app-5892c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYvP1h9XOb7crveRT7dslWAY46mg_QYCo',
    appId: '1:137420687739:android:e2867290935b7b04e155de',
    messagingSenderId: '137420687739',
    projectId: 'simple-app-5892c',
    storageBucket: 'simple-app-5892c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0o5mAwmU9suLkmbGykr9c2oQolSp09Ws',
    appId: '1:137420687739:ios:0fa0b5c8109c5a1fe155de',
    messagingSenderId: '137420687739',
    projectId: 'simple-app-5892c',
    storageBucket: 'simple-app-5892c.firebasestorage.app',
    iosBundleId: 'com.example.mySimpleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0o5mAwmU9suLkmbGykr9c2oQolSp09Ws',
    appId: '1:137420687739:ios:0fa0b5c8109c5a1fe155de',
    messagingSenderId: '137420687739',
    projectId: 'simple-app-5892c',
    storageBucket: 'simple-app-5892c.firebasestorage.app',
    iosBundleId: 'com.example.mySimpleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Z3WJXCvhuV09AuP13w1BdKnoHQxYsO0',
    appId: '1:137420687739:web:e70222f4b0983778e155de',
    messagingSenderId: '137420687739',
    projectId: 'simple-app-5892c',
    authDomain: 'simple-app-5892c.firebaseapp.com',
    storageBucket: 'simple-app-5892c.firebasestorage.app',
  );
}
